### ISSUE TITLE
Hardware Connections 

### ISSUE THREAD

**Issue by eric-meehan** [petit-miner/Blueberry-PI#6]
Hello Marcel,

I am attempting to build a board very similar to the one you have detailed here - a linux-capable single board computer with wifi.  If you are willing, I would very much like to see a schematic for your device, as I am having difficulty making a connection between the WiFi module and the V3s.  

How did you supply WiFi to the kernel?  Did you use SPI, SDIO, UART, or some other connection protocol?  Do you think it would be possible to add two WiFi modules?  If you used SDIO, the V3s seems to have multiple SDIO interfaces, so it seems feasible, though I have yet to make a connection with one. Within the OS, does the RTL8723BS appear as one of the WLAN interfaces, and would it be able to be controlled by wpa_supplicant?  

I would also like to add additional RAM and storage to the device.  Did you consider doing this?

I have a number of questions on how you managed to build this board and would love to hear back from you!

Best,
Eric

**Comment by petit-miner** [comment]
Hi Eric,
the RTL8723BS uses SDIO as main Interface. UART is only needed if you want to use Bluetooth. 
The driver for the RTL8723BS is a staging driver, so it isn't in the kernel but in a kernel module.
You will need to activate the SDIO in the devicetree including the used pins. After startup you will need to load the kernel module and then the wifi module is usable as network interface. I have only tried this with one module on SDIO1 since SDIO0 is used by my SD Card. Additional RAM isn't possible since no adress / data bus is exposed. However you can easily expand the flash by adding a bigger SD card.
If you have further questions you can email me at my email adress mentioned in the readme.
Best,
Marcel
